"""Postmortem — generated by FOLDING the journal + hypothesis store (never authored
separately, so it cannot drift from what happened, DESIGN §2.4). The confirmed hypothesis's causal chain is
the primary timeline; surviving alive hypotheses are contributing factors; refuted ones
are recorded as ruled-out (they are evidence).
"""
from __future__ import annotations

from ..domain.enums import CloseOutcome, HypothesisStatus
from ..domain.subject import SubjectRef
from ..graph.graph import Graph
from ..hypothesis.store import HypothesisStore
from ..journal.journal import Journal


def render_postmortem(subject: SubjectRef, graph: Graph, store: HypothesisStore,
                      journal: Journal, outcome: CloseOutcome | None) -> dict:
    confirmed = store.confirmed()
    timeline = sorted(
        [{"at": e.occurred_at.isoformat(), "entity": e.entity_ref, "type": e.type,
          "payload": e.payload} for e in graph.events.values()],
        key=lambda x: x["at"])
    return {
        "subject": subject.model_dump(),
        "outcome": outcome.value if outcome else "open",
        "root_cause": (
            {"statement": confirmed.statement, "root_candidate": confirmed.root_candidate,
             "confidence": confirmed.confidence.value,
             "chain": [c.model_dump(mode="json") for c in confirmed.causal_chain]}
            if confirmed else None),
        "ruled_out": [{"statement": h.statement, "basis": h.confidence.basis}
                      for h in store.hypotheses.values()
                      if h.status == HypothesisStatus.REFUTED],
        "contributing": [{"statement": h.statement, "confidence": h.confidence.value}
                         for h in store.alive()
                         if not confirmed or h.id != confirmed.id],
        "timeline": timeline,
        "narrative": [{"seq": e.seq, "phase": e.phase_id.value if e.phase_id else None,
                       "text": e.reasoning} for e in journal.phase_entries()],
    }
